spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/api/producto/**
          filters:
            - StripPrefix= 2

        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/api/cliente/**
          filters:
            - StripPrefix=2

        - id: carrito-service
          uri: lb://carrito-service
          predicates:
            - Path=/api/carrito/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

server:
  port: ${PORT:9090}