spring:
  config:
    import: eureka-client-config.yml

  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/api/producto/**
          filters:
            - StripPrefix=2

        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/api/cliente/**
          filters:
            - StripPrefix=2

        - id: carrito-service
          uri: lb://carrito-service
          predicates:
            - Path=/api/carrito/**
          filters:
            - StripPrefix=2

        - id: venta-service
          uri: lb://venta-service
          predicates:
            - Path=/api/venta/**
          filters:
            - StripPrefix=2

server:
  port: ${PORT:9090}