spring:
  config:
    import: 
      - database-config.yml
      - eureka-client-config.yml
      - circuit-breaker-config.yml
      - security-config.yml

  application:
    name: carrito-service

resilience4j:
    instances:
      cliente-service:
        base-config: default
        ignore-exceptions:
          - feign.FeignException.NotFound
          - com.electrodostore.carrito_service.exception.ClienteNotFoundException

      producto-service:
        base-config: default
        ignore-exceptions:
          - feign.FeignException.NotFound
          - com.electrodostore.carrito_service.exception.ProductoNotFoundException
          - com.electrodostore.carrito_service.exception.ProductoStockInsuficienteException

      venta-service:
        base-config: default
        ignore-exceptions:
          - feign.FeignException.NotFound
          - com.electrodostore.carrito_service.exception.ProductoNotFoundException
          - com.electrodostore.carrito_service.exception.ProductoStockInsuficienteException
          - com.electrodostore.carrito_service.exception.ClienteNotFoundException

server:
  port: ${PORT:8282}