spring:
  application:
    name: venta-service

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQLDialect

    open-in-view: false

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s

    instances:
      producto-service-read:
        base-config: default
        ignore-exceptions:
          - feign.FeignException.NotFound
          - com.electrodostore.venta_service.exception.ProductoNotFoundException

      producto-service-write:
        base-config: default
        ignoreExceptions:
          - feign.FeignException.NotFound
          - com.electrodostore.venta_service.exception.ProductoStockInsuficienteException

      cliente-service:
        base-config: default
        ignore-exceptions:
          - feign.FeignException.NotFound
          - com.electrodostore.venta_service.exception.ClienteNotFoundException


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

server:
  port: ${PORT:9191}