spring:
  config:
    import: database-config.yml

  application:
    name: venta-service

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s

    instances:
      producto-service-read:
        base-config: default
        ignore-exceptions:
          - feign.FeignException.NotFound
          - com.electrodostore.venta_service.exception.ProductoNotFoundException

      producto-service-write:
        base-config: default
        ignoreExceptions:
          - feign.FeignException.NotFound
          - com.electrodostore.venta_service.exception.ProductoStockInsuficienteException

      cliente-service:
        base-config: default
        ignore-exceptions:
          - feign.FeignException.NotFound
          - com.electrodostore.venta_service.exception.ClienteNotFoundException


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

server:
  port: ${PORT:9191}